default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRESQL_HOST'){ "db" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER"){ "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD"){ "postgres" } %>

development:
  <<: *default
  database: umanni_fullstack_developer_development

test:
  <<: *default
  database: umanni_fullstack_developer_test

production:
  <<: *default
  database: umanni_fullstack_developer_production
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
